### ISSUE TITLE
mmap error

### ISSUE THREAD

**Issue by jeffw16** [hallowelt/migrate-confluence#20] opened 2021-12-21 03:22 UTC
In 1.0.6, it will try to allocate insane amounts of memory in the `migrate-confluence compose` stage, causing a `mmap()` error (which makes sense). To be specific, it tried to allocate `140737471598624 bytes` which obviously failed. Memory is not the issue here: 8 GB of RAM and 32 GB of disk space should be plenty for a medium-sized space conversion. I've done a much bigger conversion on the same hardware specs and fared just fine. Reverting back to 1.0.4 fixed the problem. I cannot share the original dataset causing this issue, due to client privacy concerns, but it may be worth looking into this. Thanks for this great tool!

**Comment by osnard** [comment] 2021-12-27 16:48
Thanks for reporting. I will check what change could have caused this.

**Comment by DvogelHallowelt** [comment] 2021-12-28 11:28
This is probably related to https://github.com/hallowelt/migrate-confluence/issues/17
There is a fix in code review already.

Could you confirm you were using the PHAR file from 1.0.6?

**Comment by jeffw16** [comment] 2021-12-28 17:33
Yes, confirmed. Thanks!

**Comment by osnard** [comment] 2022-01-14 12:38
Duplicate of https://github.com/hallowelt/migrate-confluence/issues/17

**Closed** 2022-01-14 12:39 UTC
